# Define which plugins and packages should be run or skipped in Kibana CI pipeline
plugins:
  enabled:
    - apm
    - console
    - custom_branding
    - dashboard
    - data_views
    - discover_enhanced
    - index_management
    - infra
    - intercepts
    - lens
    - maps
    - observability
    - observability_onboarding
    - painless_lab
    - profiling
    - search_homepage
    - security_solution
    - share
    - slo
    - spaces
    - streams_app
    - dashboard
    - workflows_extensions
    - transform
    - workflows_management
  disabled:

packages:
  enabled:
    - kbn-streamlang-tests
  disabled:
    - kbn-scout # Internal scout tests are run in advance to validate Scout integrity (see .buildkite/scripts/steps/test/scout_test_run_builder.sh)
    - kbn-scout-release-testing # Release tests will run separately as part of the release process
